import matplotlib.pyplot as plt
from data import *
from utils import PlotGraph

# circle
plotter_circle = PlotGraph()
plotter_circle.plotting_base_graphs(circle_8_2ghz, circle_10ghz, circle_11_8ghz)
plt.grid(which="major", linewidth=1)
plt.grid(which="minor", linewidth=0.2)
plt.minorticks_on()
plt.tight_layout()
plt.legend(loc = "lower right")
plt.savefig(f'img/circle.png', dpi = 300)
plt.show()
plt.close(plotter_circle.fig)

# big_circle
plotter_big_circle = PlotGraph()
plotter_big_circle.plotting_base_graphs(big_circle_8_2ghz, big_circle_10ghz, big_circle_11_8ghz)
plt.grid(which="major", linewidth=1)
plt.grid(which="minor", linewidth=0.2)
plt.minorticks_on()
plt.tight_layout()
plt.legend(loc = "lower right")
plt.savefig(f'img/big_circle.png', dpi = 300)
plt.show()
plt.close(plotter_big_circle.fig)

# max_circle
plotter_max_circle = PlotGraph()
plotter_max_circle.plotting_base_graphs(max_circle_8_2ghz, max_circle_10ghz, max_circle_11_8ghz)
plotter_max_circle.plot_additional_graph(cut_x_25, max_circle_8_2ghz_dop, label='8.2 GHz доп.', linestyle='-', color='k')
plotter_max_circle.plot_additional_graph(cut_x_25, max_circle_10ghz_dop, label='10 GHz доп.', linestyle='--', color='k')
plotter_max_circle.plot_additional_graph(cut_x_25, max_circle_11_8ghz_dop, label='11.8 GHz доп.', linestyle=':', color='k')
plt.grid(which="major", linewidth=1)
plt.grid(which="minor", linewidth=0.2)
plt.minorticks_on()
plt.tight_layout()
plt.legend(loc = "lower right")
plt.savefig(f'img/max_circle_add.png', dpi = 300)
plt.show()
plt.close(plotter_max_circle.fig)

# square
plotter_square = PlotGraph()
plotter_square.plotting_base_graphs(square_8_2_ghz, square_10_ghz, square_11_8ghz)
plt.grid(which="major", linewidth=1)
plt.grid(which="minor", linewidth=0.2)
plt.minorticks_on()
plt.tight_layout()
plt.legend(loc = "lower right")
plt.savefig(f'img/square.png', dpi = 300)
plt.show()
plt.close(plotter_square.fig)

# nonsymmetrical
# Построение каждого графика отдельно (т.е. через plot_additional_graph) позволяет убирать комментами ненужные графики для детальных сравнений
plotter_nonsymmetrical = PlotGraph()
plotter_nonsymmetrical.plot_additional_graph(full_x, nonsymmetrical_8_2_ghz, label='8.2 GHz', linestyle='-', color='b')
plotter_nonsymmetrical.plot_additional_graph(full_x, nonsymmetrical_10_ghz, label='10 GHz', linestyle='-', color='r')
plotter_nonsymmetrical.plot_additional_graph(cut_x_60, nonsymmetrical_11_8ghz, label='11.8 GHz', linestyle='-', color='g')
plotter_nonsymmetrical.plot_additional_graph(cut_x_25, nonsymmetrical_11_8ghz_DOP, label='11.8 GHz additional', linestyle='--', color='k')
plotter_nonsymmetrical.plot_additional_graph(cut_x_50, nonsymmetrical_8_2_ghz_reverse, label='8.2 GHz reverse', linestyle='-', color='b')
plotter_nonsymmetrical.plot_additional_graph(cut_x_50, nonsymmetrical_10_ghz_reverse, label='10 GHz reverse', linestyle='-', color='r')
plotter_nonsymmetrical.plot_additional_graph(cut_x_50, nonsymmetrical_11_8ghz_reverse, label='11.8 GHz reverse', linestyle='-', color='g')
plt.grid(which="major", linewidth=1)
plt.grid(which="minor", linewidth=0.2)
plt.minorticks_on()
plt.tight_layout()
plt.savefig(f'img/nonsymmetrical.png', dpi = 300)
plt.show()
plt.close(plotter_nonsymmetrical.fig)

# z
# Построение каждого графика отдельно (т.е. через plot_additional_graph) позволяет убирать комментами ненужные графики для детальных сравнений
plotter_z = PlotGraph()
plotter_z.plot_additional_graph(cut_x_50,z_8_2_ghz,label = '8.2 GHz', linestyle = '-', color = 'b')
plotter_z.plot_additional_graph(cut_x_50,z_10_ghz,label = '10 GHz', linestyle = '-', color = 'r')
plotter_z.plot_additional_graph(cut_x_50,z_11_8_ghz,label = '11.8 GHz', linestyle = '-', color = 'g')
plotter_z.plot_additional_graph(cut_x_50,z_8_2_ghz_reverse,label = '8.2 GHz reverse', linestyle = '-', color = 'b')
plotter_z.plot_additional_graph(cut_x_50,z_10_ghz_reverse,label = '10 GHz reverse', linestyle = '-', color = 'r')
plotter_z.plot_additional_graph(cut_x_50,z_11_8_ghz_reverse,label = '11.8 GHz reverse', linestyle = '-', color = 'g')
plt.grid(which="major", linewidth=1)
plt.grid(which="minor", linewidth=0.2)
plt.minorticks_on()
plt.tight_layout()
plt.savefig(f'img/z.png', dpi = 300)
plt.show()
plt.close(plotter_z.fig)

# ge
# Построение каждого графика отдельно (т.е. через plot_additional_graph) позволяет убирать комментами ненужные графики для детальных сравнений
plotter_ge = PlotGraph()
plotter_ge.plot_additional_graph(cut_x_50,ge_8_2_ghz,label = '8.2 GHz', linestyle = '-', color = 'b')
plotter_ge.plot_additional_graph(cut_x_50,ge_10_ghz,label = '10 GHz', linestyle = '-', color = 'r')
plotter_ge.plot_additional_graph(cut_x_50,ge_11_8_ghz,label = '11.8 GHz', linestyle = '-', color = 'g')
plotter_ge.plot_additional_graph(cut_x_50,ge_8_2_ghz_reverse,label = '8.2 GHz reverse', linestyle = '-', color = 'b')
plotter_ge.plot_additional_graph(cut_x_50,ge_10_ghz_reverse,label = '10 GHz reverse', linestyle = '-', color = 'r')
plotter_ge.plot_additional_graph(cut_x_50,ge_11_8_ghz_reverse,label = '11.8 GHz reverse', linestyle = '-', color = 'g')
plt.grid(which="major", linewidth=1)
plt.grid(which="minor", linewidth=0.2)
plt.minorticks_on()
plt.tight_layout()
plt.savefig(f'img/ge_118_compare.png', dpi = 300)
plt.show()
plt.close(plotter_ge.fig)