import matplotlib.pyplot as plt
from data import *
from utils import PlotGraph

# circle
# plotter_circle = PlotGraph()
# plotter_circle.plotting_base_graphs(circle_8_2ghz, circle_10ghz, circle_11_8ghz, applyGauss=False)
# plotter_circle.plot_additional_graph(cut_x_50, circle_17_8ghz, applyGauss=False, label = "17.8 GHz")
# plt.grid(which="major", linewidth=1)
# plt.grid(which="minor", linewidth=0.2)
# plt.minorticks_on()
# plt.tight_layout()
# plt.legend(loc = "lower right")
# plt.savefig(f'img/circle.png', dpi = 300)
# plt.show()
# plt.close(plotter_circle.fig)

# big_circle
# plotter_big_circle = PlotGraph()
# plotter_big_circle.plotting_base_graphs(big_circle_8_2ghz, big_circle_10ghz, big_circle_11_8ghz, applyGauss=False)
# plotter_big_circle.plot_additional_graph(cut_x_50, big_circle_17_8ghz, applyGauss=False, label = "17.8 GHz")
# plt.grid(which="major", linewidth=1)
# plt.grid(which="minor", linewidth=0.2)
# plt.minorticks_on()
# plt.tight_layout()
# plt.legend(loc = "lower right")
# plt.savefig(f'img/big_circle.png', dpi = 300)
# plt.show()
# plt.close(plotter_big_circle.fig)

# max_circle
# plotter_max_circle = PlotGraph()
# plotter_max_circle.plotting_base_graphs(max_circle_8_2ghz, max_circle_10ghz, max_circle_11_8ghz, applyGauss=False)
# plotter_max_circle.plot_additional_graph(cut_x_50, max_circle_17_8ghz, label='17.8 GHz', applyGauss=False)
# plotter_max_circle.plot_additional_graph(cut_x_25, max_circle_8_2ghz_dop, applyGauss=False, label='8.2 GHz доп.', linestyle='-', color='k')
# plotter_max_circle.plot_additional_graph(cut_x_25, max_circle_10ghz_dop, applyGauss=False, label='10 GHz доп.', linestyle='--', color='k')
# plotter_max_circle.plot_additional_graph(cut_x_25, max_circle_11_8ghz_dop, applyGauss=False, label='11.8 GHz доп.', linestyle=':', color='k')
# plt.grid(which="major", linewidth=1)
# plt.grid(which="minor", linewidth=0.2)
# plt.minorticks_on()
# plt.tight_layout()
# plt.legend(loc = "lower right")
# plt.savefig(f'img/max_circle_base_and_add_gauss.png', dpi = 300)
# plt.show()
# plt.close(plotter_max_circle.fig)

# square
# plotter_square = PlotGraph()
# plotter_square.plotting_base_graphs(square_8_2_ghz, square_10_ghz, square_11_8ghz, applyGauss=False)
# plotter_square.plot_additional_graph(cut_x_50, square_17_8_ghz, label='17.8 GHz', applyGauss=False)
# plt.grid(which="major", linewidth=1)
# plt.grid(which="minor", linewidth=0.2)
# plt.minorticks_on()
# plt.tight_layout()
# plt.legend(loc = "lower right")
# plt.savefig(f'img/square.png', dpi = 300)
# plt.show()
# plt.close(plotter_square.fig)

# nonsymmetrical
# Построение каждого графика отдельно (т.е. через plot_additional_graph) позволяет убирать комментами ненужные графики для детальных сравнений
# plotter_nonsymmetrical = PlotGraph()
# plotter_nonsymmetrical.plot_additional_graph(full_x, nonsymmetrical_8_2_ghz, label='8.2 GHz', linestyle='-', color='b', applyGauss=False)
# plotter_nonsymmetrical.plot_additional_graph(full_x, nonsymmetrical_10_ghz, label='10 GHz', linestyle='-', color='b', applyGauss=False)
# plotter_nonsymmetrical.plot_additional_graph(cut_x_60, nonsymmetrical_11_8ghz, label='11.8 GHz', linestyle='-', color='b', applyGauss=False)
# plotter_nonsymmetrical.plot_additional_graph(cut_x_25, nonsymmetrical_11_8ghz_DOP, label='11.8 GHz additional', linestyle='--', color='k', applyGauss=False)
# plotter_nonsymmetrical.plot_additional_graph(cut_x_50, nonsymmetrical_8_2_ghz_reverse, label='8.2 GHz reverse', linestyle='-', color='b', applyGauss=False)
# plotter_nonsymmetrical.plot_additional_graph(cut_x_50, nonsymmetrical_10_ghz_reverse, label='10 GHz reverse', linestyle='-', color='r', applyGauss=False)
# plotter_nonsymmetrical.plot_additional_graph(cut_x_50, nonsymmetrical_11_8ghz_reverse, label='11.8 GHz reverse', linestyle='-', color='r', applyGauss=False)
# plt.grid(which="major", linewidth=1)
# plt.grid(which="minor", linewidth=0.2)
# plt.minorticks_on()
# plt.tight_layout()
# plt.savefig(f'img/nonsymmetrical_118_compare_gauss.png', dpi = 300)
# plt.show()
# plt.close(plotter_nonsymmetrical.fig)

# z
# Построение каждого графика отдельно (т.е. через plot_additional_graph) позволяет убирать комментами ненужные графики для детальных сравнений
# plotter_z = PlotGraph()
# plotter_z.plot_additional_graph(cut_x_50,z_8_2_ghz,label = '8.2 GHz', linestyle = '-', color = 'b', applyGauss=False)
# plotter_z.plot_additional_graph(cut_x_50,z_10_ghz,label = '10 GHz', linestyle = '-', color = 'b', applyGauss=False)
# plotter_z.plot_additional_graph(cut_x_50,z_11_8_ghz,label = '11.8 GHz', linestyle = '-', color = 'b', applyGauss=False)
# plotter_z.plot_additional_graph(cut_x_50,z_17_8_ghz, label = '17.8 GHz', color = 'b', applyGauss=False)
# plotter_z.plot_additional_graph(cut_x_50,z_8_2_ghz_reverse,label = '8.2 GHz reverse', linestyle = '-', color = 'r',applyGauss=False)
# plotter_z.plot_additional_graph(cut_x_50,z_10_ghz_reverse,label = '10 GHz reverse', linestyle = '-', color = 'r',applyGauss=False)
# plotter_z.plot_additional_graph(cut_x_50,z_11_8_ghz_reverse,label = '11.8 GHz reverse', linestyle = '-', color = 'r',applyGauss=False)
# plotter_z.plot_additional_graph(cut_x_26,z_17_8_ghz_reverse, label = '17.8 GHz reverse', color = 'r', applyGauss=False)
# plt.grid(which="major", linewidth=1)
# plt.grid(which="minor", linewidth=0.2)
# plt.minorticks_on()
# plt.tight_layout()
# plt.savefig(f'img/z_178_compare_reverse_gauss.png', dpi = 300)
# plt.show()
# plt.close(plotter_z.fig)

# ge
# Построение каждого графика отдельно (т.е. через plot_additional_graph) позволяет убирать комментами ненужные графики для детальных сравнений
# plotter_ge = PlotGraph()
# plotter_ge.plot_additional_graph(cut_x_50,ge_8_2_ghz,label = '8.2 GHz', linestyle = '-', color = 'b', applyGauss=False)
# plotter_ge.plot_additional_graph(cut_x_50,ge_10_ghz,label = '10 GHz', linestyle = '-', color = 'b', applyGauss=False)
# plotter_ge.plot_additional_graph(cut_x_50,ge_11_8_ghz,label = '11.8 GHz', linestyle = '-', color = 'b', applyGauss=False)
# plotter_ge.plot_additional_graph(cut_x_26, ge_17_8_ghz_dop, label = '17.8 GHz', color = 'b', applyGauss=False)
# plotter_ge.plot_additional_graph(cut_x_50,ge_8_2_ghz_reverse,label = '8.2 GHz reverse', linestyle = '-', color = 'r', applyGauss=False)
# plotter_ge.plot_additional_graph(cut_x_50,ge_10_ghz_reverse,label = '10 GHz reverse', linestyle = '-', color = 'r', applyGauss=False)
# plotter_ge.plot_additional_graph(cut_x_50,ge_11_8_ghz_reverse,label = '11.8 GHz reverse', linestyle = '-', color = 'r',  applyGauss=False)
# plotter_ge.plot_additional_graph(cut_x_50, ge_17_8_ghz_reverse, label = '17.8 GHz reverse', color = 'r', applyGauss=False)
# plt.grid(which="major", linewidth=1)
# plt.grid(which="minor", linewidth=0.2)
# plt.minorticks_on()
# plt.tight_layout()
# plt.savefig(f'img/ge_118_compare_gauss.png', dpi = 300)
# plt.show()
# plt.close(plotter_ge.fig)

#piform
# plotter_piform = PlotGraph()
# plotter_piform.plot_additional_graph(cut_x_50,pirform_8_2_ghz,label = '8.2 GHz', linestyle = '-', color = 'b', applyGauss=False)
# plotter_piform.plot_additional_graph(cut_x_50,pirform_10_ghz,label = '10 GHz', linestyle = '-', color = 'b', applyGauss=False)
# plotter_piform.plot_additional_graph(cut_x_50,pirform_11_8_ghz_again,label = '11.8 GHz', linestyle = '-', color = 'b', applyGauss=False)
# plotter_piform.plot_additional_graph(cut_x_50,pirform_17_8_ghz, label = '17.8 GHz', color = 'b', applyGauss=False)
# plotter_piform.plot_additional_graph(cut_x_26,pirform_8_2_ghz_reverse,label = '8.2 GHz reverse', linestyle = '-', color = 'r', applyGauss=False)
# plotter_piform.plot_additional_graph(cut_x_26,pirform_10_ghz_reverse,label = '10 GHz reverse', linestyle = '-', color = 'r', applyGauss=False)
# plotter_piform.plot_additional_graph(cut_x_26,pirform_11_8_ghz_reverse,label = '11.8 GHz reverse', linestyle = '-', color = 'r',  applyGauss=False)
# plotter_piform.plot_additional_graph(cut_x_26,pirform_17_8_ghz_reverse, label = '17.8 GHz reverse', color = 'r', applyGauss=False)
# plt.grid(which="major", linewidth=1)
# plt.grid(which="minor", linewidth=0.2)
# plt.minorticks_on()
# plt.tight_layout()
# plt.savefig(f'img/piform_178_compare.png', dpi = 300)
# plt.show()
# plt.close(plotter_piform.fig)

#amogus
# plotter_amogus = PlotGraph()
# plotter_amogus.plot_additional_graph(cut_x_50,amogus_8_2_ghz,label = '8.2 GHz', linestyle = '-', color = 'b', applyGauss=False)
# plotter_amogus.plot_additional_graph(cut_x_50,amogus_10_ghz,label = '10 GHz', linestyle = '-', color = 'b', applyGauss=True, gaussAlpha=0.1)
# plotter_amogus.plot_additional_graph(cut_x_50,amogus_11_8_ghz,label = '11.8 GHz', linestyle = '-', color = 'b', applyGauss=False)
# plotter_amogus.plot_additional_graph(cut_x_26,amogus_17_8_ghz, label = '17.8 GHz', color = 'b', applyGauss=False)
# plotter_amogus.plot_additional_graph(cut_x_26,amogus_8_2_ghz_reverse,label = '8.2 GHz reverse', linestyle = '-', color = 'r', applyGauss=False)
# plotter_amogus.plot_additional_graph(cut_x_26,amogus_10_ghz_reverse,label = '10 GHz reverse', linestyle = '-', color = 'r', applyGauss=True,gaussAlpha=0.1)
# plotter_amogus.plot_additional_graph(cut_x_26,amogus_11_8_ghz_reverse,label = '11.8 GHz reverse', linestyle = '-', color = 'r',  applyGauss=False)
# plotter_amogus.plot_additional_graph(cut_x_50,amogus_17_8_ghz_reverse, label = '17.8 GHz reverse', color = 'r', applyGauss=False)
# plt.grid(which="major", linewidth=1)
# plt.grid(which="minor", linewidth=0.2)
# plt.minorticks_on()
# plt.tight_layout()
# plt.savefig(f'img/amogus_10_compare.png', dpi = 300)
# plt.show()
# plt.close(plotter_amogus.fig)

#rx_amogus
# plotter_amogus = PlotGraph()
# plotter_amogus.plot_additional_graph(cut_x_50, rx_8_2_ghz_amogus, label = '8.2 GHz RX', color = 'b', applyGauss=True)
# plotter_amogus.plot_additional_graph(cut_x_50, amogus_8_2_ghz,label = '8.2 GHz object', color = 'r', applyGauss=True)

# plotter_amogus.plot_additional_graph(cut_x_26, rx_8_2_ghz_amogus_dop_cut_reverse, label = '8.2 GHz RX reversed', color = 'b', applyGauss=True)
# plotter_amogus.plot_additional_graph(cut_x_26, amogus_8_2_ghz_reverse,label = '8.2 GHz object reversed', color = 'r', applyGauss=True)

# plotter_amogus.plot_additional_graph(cut_x_50, rx_10_ghz_amogus, label = '10 GHz RX', color = 'b', applyGauss=True)
# plotter_amogus.plot_additional_graph(cut_x_50, amogus_10_ghz,label = '10 GHz object', color = 'r', applyGauss=True)

# plotter_amogus.plot_additional_graph(cut_x_26, rx_10_ghz_amogus_dop_cut_reverse, label = '10 GHz RX reversed', color = 'b', applyGauss=True)
# plotter_amogus.plot_additional_graph(cut_x_26, amogus_10_ghz_reverse,label = '10 GHz object reversed', color = 'r', applyGauss=True)

# plotter_amogus.plot_additional_graph(cut_x_50, rx_11_8_ghz_amogus, label = '11.8 GHz RX', color = 'b', applyGauss=True)
# plotter_amogus.plot_additional_graph(cut_x_50, amogus_11_8_ghz,label = '11.8 GHz object', color = 'r', applyGauss=True)

# plotter_amogus.plot_additional_graph(cut_x_26, rx_11_8_ghz_amogus_dop_cut_reverse, label = '11.8 GHz RX reversed', color = 'b', applyGauss=True)
# plotter_amogus.plot_additional_graph(cut_x_26, amogus_11_8_ghz_reverse,label = '11.8 GHz object reversed', color = 'r', applyGauss=True)

# plt.grid(which="major", linewidth=1)
# plt.grid(which="minor", linewidth=0.2)
# plt.minorticks_on()
# plt.tight_layout()
# plt.savefig(f'img/amogus_82_rx_and_object_compare_reverse_gauss.png', dpi = 300)
# plt.show()
# plt.close(plotter_amogus.fig)